# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Freenove\Desktop\3wd\PyQt_Test\main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(780, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(780, 600))
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/logo_Mini"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.btn_Up = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Up.setGeometry(QtCore.QRect(560, 400, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_Up.setFont(font)
        self.btn_Up.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_Up.setObjectName("btn_Up")
        self.btn_Left = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Left.setGeometry(QtCore.QRect(480, 440, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_Left.setFont(font)
        self.btn_Left.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_Left.setObjectName("btn_Left")
        self.btn_Down = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Down.setGeometry(QtCore.QRect(560, 480, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_Down.setFont(font)
        self.btn_Down.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_Down.setObjectName("btn_Down")
        self.btn_Right = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Right.setGeometry(QtCore.QRect(640, 440, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_Right.setFont(font)
        self.btn_Right.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_Right.setObjectName("btn_Right")
        self.slider_Camera = QtWidgets.QSlider(self.centralWidget)
        self.slider_Camera.setGeometry(QtCore.QRect(520, 350, 160, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.slider_Camera.setFont(font)
        self.slider_Camera.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider_Camera.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slider_Camera.setMinimum(1)
        self.slider_Camera.setMaximum(30)
        self.slider_Camera.setProperty("value", 10)
        self.slider_Camera.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Camera.setObjectName("slider_Camera")
        self.btn_Forward = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Forward.setGeometry(QtCore.QRect(110, 400, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_Forward.setFont(font)
        self.btn_Forward.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_Forward.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn_Forward.setAcceptDrops(False)
        self.btn_Forward.setObjectName("btn_Forward")
        self.btn_TurnLeft = QtWidgets.QPushButton(self.centralWidget)
        self.btn_TurnLeft.setGeometry(QtCore.QRect(30, 440, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_TurnLeft.setFont(font)
        self.btn_TurnLeft.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_TurnLeft.setObjectName("btn_TurnLeft")
        self.btn_TurnRight = QtWidgets.QPushButton(self.centralWidget)
        self.btn_TurnRight.setGeometry(QtCore.QRect(190, 440, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_TurnRight.setFont(font)
        self.btn_TurnRight.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_TurnRight.setObjectName("btn_TurnRight")
        self.btn_Backward = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Backward.setGeometry(QtCore.QRect(110, 480, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_Backward.setFont(font)
        self.btn_Backward.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_Backward.setObjectName("btn_Backward")
        self.slider_Speed = QtWidgets.QSlider(self.centralWidget)
        self.slider_Speed.setGeometry(QtCore.QRect(280, 370, 22, 160))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.slider_Speed.setFont(font)
        self.slider_Speed.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider_Speed.setMaximum(100)
        self.slider_Speed.setProperty("value", 50)
        self.slider_Speed.setOrientation(QtCore.Qt.Vertical)
        self.slider_Speed.setObjectName("slider_Speed")
        self.slider_Direction = QtWidgets.QSlider(self.centralWidget)
        self.slider_Direction.setGeometry(QtCore.QRect(70, 530, 160, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.slider_Direction.setFont(font)
        self.slider_Direction.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider_Direction.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slider_Direction.setMinimum(10)
        self.slider_Direction.setMaximum(60)
        self.slider_Direction.setPageStep(5)
        self.slider_Direction.setProperty("value", 35)
        self.slider_Direction.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Direction.setObjectName("slider_Direction")
        self.label_tAngle = QtWidgets.QLabel(self.centralWidget)
        self.label_tAngle.setGeometry(QtCore.QRect(70, 560, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_tAngle.setFont(font)
        self.label_tAngle.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_tAngle.setObjectName("label_tAngle")
        self.btn_Connect = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Connect.setGeometry(QtCore.QRect(260, 330, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_Connect.setFont(font)
        self.btn_Connect.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_Connect.setIconSize(QtCore.QSize(64, 64))
        self.btn_Connect.setAutoRepeat(False)
        self.btn_Connect.setObjectName("btn_Connect")
        self.logo = QtWidgets.QGraphicsView(self.centralWidget)
        self.logo.setEnabled(False)
        self.logo.setGeometry(QtCore.QRect(450, 10, 320, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.logo.setFont(font)
        self.logo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.logo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.logo.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.logo.setForegroundBrush(brush)
        self.logo.setObjectName("logo")
        self.label_Speed = QtWidgets.QLabel(self.centralWidget)
        self.label_Speed.setGeometry(QtCore.QRect(280, 560, 54, 12))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_Speed.setFont(font)
        self.label_Speed.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_Speed.setObjectName("label_Speed")
        self.label_Scale = QtWidgets.QLabel(self.centralWidget)
        self.label_Scale.setGeometry(QtCore.QRect(470, 350, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_Scale.setFont(font)
        self.label_Scale.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_Scale.setObjectName("label_Scale")
        self.lcd_tAngle = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcd_tAngle.setGeometry(QtCore.QRect(150, 550, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lcd_tAngle.setFont(font)
        self.lcd_tAngle.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lcd_tAngle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_tAngle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_tAngle.setSmallDecimalPoint(False)
        self.lcd_tAngle.setNumDigits(2)
        self.lcd_tAngle.setDigitCount(2)
        self.lcd_tAngle.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_tAngle.setProperty("value", 35.0)
        self.lcd_tAngle.setProperty("intValue", 35)
        self.lcd_tAngle.setObjectName("lcd_tAngle")
        self.lcd_Speed = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcd_Speed.setGeometry(QtCore.QRect(260, 530, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lcd_Speed.setFont(font)
        self.lcd_Speed.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_Speed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_Speed.setNumDigits(3)
        self.lcd_Speed.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Speed.setProperty("value", 50.0)
        self.lcd_Speed.setObjectName("lcd_Speed")
        self.lineEdit_IP_Addr = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_IP_Addr.setEnabled(True)
        self.lineEdit_IP_Addr.setGeometry(QtCore.QRect(120, 330, 141, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lineEdit_IP_Addr.setFont(font)
        self.lineEdit_IP_Addr.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_IP_Addr.setObjectName("lineEdit_IP_Addr")
        self.lcd_Scale = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcd_Scale.setGeometry(QtCore.QRect(690, 340, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lcd_Scale.setFont(font)
        self.lcd_Scale.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lcd_Scale.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_Scale.setNumDigits(2)
        self.lcd_Scale.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Scale.setProperty("value", 10.0)
        self.lcd_Scale.setObjectName("lcd_Scale")
        self.label_IP_Addr = QtWidgets.QLabel(self.centralWidget)
        self.label_IP_Addr.setGeometry(QtCore.QRect(10, 330, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_IP_Addr.setFont(font)
        self.label_IP_Addr.setObjectName("label_IP_Addr")
        self.webView = QtWebKitWidgets.QWebView(self.centralWidget)
        self.webView.setEnabled(True)
        self.webView.setGeometry(QtCore.QRect(10, 10, 400, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.webView.setFont(font)
        self.webView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.webView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.webView.setAutoFillBackground(False)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setZoomFactor(1.200000047683716)
        self.webView.setObjectName("webView")
        self.btn_RGB_R = QtWidgets.QPushButton(self.centralWidget)
        self.btn_RGB_R.setGeometry(QtCore.QRect(340, 370, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_RGB_R.setFont(font)
        self.btn_RGB_R.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_RGB_R.setObjectName("btn_RGB_R")
        self.btn_RGB_G = QtWidgets.QPushButton(self.centralWidget)
        self.btn_RGB_G.setGeometry(QtCore.QRect(340, 400, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_RGB_G.setFont(font)
        self.btn_RGB_G.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_RGB_G.setObjectName("btn_RGB_G")
        self.btn_RGB_B = QtWidgets.QPushButton(self.centralWidget)
        self.btn_RGB_B.setGeometry(QtCore.QRect(340, 430, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_RGB_B.setFont(font)
        self.btn_RGB_B.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_RGB_B.setObjectName("btn_RGB_B")
        self.btn_Buzzer = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Buzzer.setGeometry(QtCore.QRect(340, 460, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_Buzzer.setFont(font)
        self.btn_Buzzer.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_Buzzer.setObjectName("btn_Buzzer")
        self.slider_Camera_H = QtWidgets.QSlider(self.centralWidget)
        self.slider_Camera_H.setGeometry(QtCore.QRect(520, 530, 160, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.slider_Camera_H.setFont(font)
        self.slider_Camera_H.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider_Camera_H.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.slider_Camera_H.setMaximum(180)
        self.slider_Camera_H.setProperty("value", 90)
        self.slider_Camera_H.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Camera_H.setObjectName("slider_Camera_H")
        self.slider_Camera_V = QtWidgets.QSlider(self.centralWidget)
        self.slider_Camera_V.setGeometry(QtCore.QRect(730, 370, 22, 160))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.slider_Camera_V.setFont(font)
        self.slider_Camera_V.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider_Camera_V.setMaximum(180)
        self.slider_Camera_V.setProperty("value", 90)
        self.slider_Camera_V.setOrientation(QtCore.Qt.Vertical)
        self.slider_Camera_V.setObjectName("slider_Camera_V")
        self.lcd_Camera_H = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcd_Camera_H.setGeometry(QtCore.QRect(570, 550, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lcd_Camera_H.setFont(font)
        self.lcd_Camera_H.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lcd_Camera_H.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_Camera_H.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_Camera_H.setSmallDecimalPoint(False)
        self.lcd_Camera_H.setNumDigits(3)
        self.lcd_Camera_H.setDigitCount(3)
        self.lcd_Camera_H.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Camera_H.setProperty("value", 90.0)
        self.lcd_Camera_H.setProperty("intValue", 90)
        self.lcd_Camera_H.setObjectName("lcd_Camera_H")
        self.lcd_Camera_V = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcd_Camera_V.setGeometry(QtCore.QRect(710, 530, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lcd_Camera_V.setFont(font)
        self.lcd_Camera_V.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lcd_Camera_V.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_Camera_V.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_Camera_V.setSmallDecimalPoint(False)
        self.lcd_Camera_V.setNumDigits(3)
        self.lcd_Camera_V.setDigitCount(3)
        self.lcd_Camera_V.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Camera_V.setProperty("value", 90.0)
        self.lcd_Camera_V.setProperty("intValue", 90)
        self.lcd_Camera_V.setObjectName("lcd_Camera_V")
        self.groupBox_Servo = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_Servo.setGeometry(QtCore.QRect(450, 200, 291, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_Servo.setFont(font)
        self.groupBox_Servo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_Servo.setObjectName("groupBox_Servo")
        self.slider_FineServo1 = QtWidgets.QSlider(self.groupBox_Servo)
        self.slider_FineServo1.setGeometry(QtCore.QRect(70, 20, 160, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.slider_FineServo1.setFont(font)
        self.slider_FineServo1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider_FineServo1.setMinimum(-10)
        self.slider_FineServo1.setMaximum(10)
        self.slider_FineServo1.setPageStep(1)
        self.slider_FineServo1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_FineServo1.setObjectName("slider_FineServo1")
        self.slider_FineServo2 = QtWidgets.QSlider(self.groupBox_Servo)
        self.slider_FineServo2.setGeometry(QtCore.QRect(70, 50, 160, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.slider_FineServo2.setFont(font)
        self.slider_FineServo2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider_FineServo2.setMinimum(-10)
        self.slider_FineServo2.setMaximum(10)
        self.slider_FineServo2.setPageStep(1)
        self.slider_FineServo2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_FineServo2.setObjectName("slider_FineServo2")
        self.slider_FineServo3 = QtWidgets.QSlider(self.groupBox_Servo)
        self.slider_FineServo3.setGeometry(QtCore.QRect(70, 80, 160, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.slider_FineServo3.setFont(font)
        self.slider_FineServo3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider_FineServo3.setMinimum(-10)
        self.slider_FineServo3.setMaximum(10)
        self.slider_FineServo3.setPageStep(1)
        self.slider_FineServo3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_FineServo3.setObjectName("slider_FineServo3")
        self.slider_FineServo4 = QtWidgets.QSlider(self.groupBox_Servo)
        self.slider_FineServo4.setGeometry(QtCore.QRect(70, 110, 160, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.slider_FineServo4.setFont(font)
        self.slider_FineServo4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider_FineServo4.setMinimum(-10)
        self.slider_FineServo4.setMaximum(10)
        self.slider_FineServo4.setPageStep(1)
        self.slider_FineServo4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_FineServo4.setObjectName("slider_FineServo4")
        self.label_FineServo_1 = QtWidgets.QLabel(self.groupBox_Servo)
        self.label_FineServo_1.setGeometry(QtCore.QRect(20, 20, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_FineServo_1.setFont(font)
        self.label_FineServo_1.setObjectName("label_FineServo_1")
        self.label_FineServo_2 = QtWidgets.QLabel(self.groupBox_Servo)
        self.label_FineServo_2.setGeometry(QtCore.QRect(20, 50, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_FineServo_2.setFont(font)
        self.label_FineServo_2.setObjectName("label_FineServo_2")
        self.label_FineServo_3 = QtWidgets.QLabel(self.groupBox_Servo)
        self.label_FineServo_3.setGeometry(QtCore.QRect(20, 80, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_FineServo_3.setFont(font)
        self.label_FineServo_3.setObjectName("label_FineServo_3")
        self.label_FineServo_4 = QtWidgets.QLabel(self.groupBox_Servo)
        self.label_FineServo_4.setGeometry(QtCore.QRect(20, 110, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_FineServo_4.setFont(font)
        self.label_FineServo_4.setObjectName("label_FineServo_4")
        self.lcd_FineServo_1 = QtWidgets.QLCDNumber(self.groupBox_Servo)
        self.lcd_FineServo_1.setGeometry(QtCore.QRect(240, 20, 41, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lcd_FineServo_1.setFont(font)
        self.lcd_FineServo_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lcd_FineServo_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_FineServo_1.setNumDigits(3)
        self.lcd_FineServo_1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_FineServo_1.setProperty("value", 0.0)
        self.lcd_FineServo_1.setObjectName("lcd_FineServo_1")
        self.lcd_FineServo_2 = QtWidgets.QLCDNumber(self.groupBox_Servo)
        self.lcd_FineServo_2.setGeometry(QtCore.QRect(240, 50, 41, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lcd_FineServo_2.setFont(font)
        self.lcd_FineServo_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lcd_FineServo_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_FineServo_2.setNumDigits(3)
        self.lcd_FineServo_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_FineServo_2.setProperty("value", 0.0)
        self.lcd_FineServo_2.setObjectName("lcd_FineServo_2")
        self.lcd_FineServo_3 = QtWidgets.QLCDNumber(self.groupBox_Servo)
        self.lcd_FineServo_3.setGeometry(QtCore.QRect(240, 80, 41, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lcd_FineServo_3.setFont(font)
        self.lcd_FineServo_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lcd_FineServo_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_FineServo_3.setNumDigits(3)
        self.lcd_FineServo_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_FineServo_3.setProperty("value", 0.0)
        self.lcd_FineServo_3.setObjectName("lcd_FineServo_3")
        self.lcd_FineServo_4 = QtWidgets.QLCDNumber(self.groupBox_Servo)
        self.lcd_FineServo_4.setGeometry(QtCore.QRect(240, 110, 41, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lcd_FineServo_4.setFont(font)
        self.lcd_FineServo_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lcd_FineServo_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_FineServo_4.setNumDigits(3)
        self.lcd_FineServo_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_FineServo_4.setProperty("value", 0.0)
        self.lcd_FineServo_4.setObjectName("lcd_FineServo_4")
        self.btn_Home = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Home.setGeometry(QtCore.QRect(570, 440, 55, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btn_Home.setFont(font)
        self.btn_Home.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_Home.setObjectName("btn_Home")
        self.btn_Mode = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Mode.setGeometry(QtCore.QRect(340, 530, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_Mode.setFont(font)
        self.btn_Mode.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_Mode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_Mode.setObjectName("btn_Mode")
        self.label_Mode = QtWidgets.QLabel(self.centralWidget)
        self.label_Mode.setGeometry(QtCore.QRect(370, 490, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.label_Mode.setFont(font)
        self.label_Mode.setObjectName("label_Mode")
        self.wgt_Drawing = QtWidgets.QWidget(self.centralWidget)
        self.wgt_Drawing.setGeometry(QtCore.QRect(260, 10, 181, 121))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.wgt_Drawing.setFont(font)
        self.wgt_Drawing.setObjectName("wgt_Drawing")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.slider_Direction.valueChanged['int'].connect(self.lcd_tAngle.display)
        self.slider_Speed.valueChanged['int'].connect(self.lcd_Speed.display)
        self.slider_Camera.valueChanged['int'].connect(self.lcd_Scale.display)
        self.slider_Camera_H.valueChanged['int'].connect(self.lcd_Camera_H.display)
        self.slider_Camera_V.valueChanged['int'].connect(self.lcd_Camera_V.display)
        self.slider_FineServo1.valueChanged['int'].connect(self.lcd_FineServo_1.display)
        self.slider_FineServo2.valueChanged['int'].connect(self.lcd_FineServo_2.display)
        self.slider_FineServo3.valueChanged['int'].connect(self.lcd_FineServo_3.display)
        self.slider_FineServo4.valueChanged['int'].connect(self.lcd_FineServo_4.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Freenove Client for Smart Car"))
        self.btn_Up.setText(_translate("MainWindow", "UP"))
        self.btn_Left.setText(_translate("MainWindow", "LEFT"))
        self.btn_Down.setText(_translate("MainWindow", "DOWN"))
        self.btn_Right.setText(_translate("MainWindow", "RIGHT"))
        self.btn_Forward.setText(_translate("MainWindow", "FORWARD"))
        self.btn_TurnLeft.setText(_translate("MainWindow", "TURN LEFT"))
        self.btn_TurnRight.setText(_translate("MainWindow", "TURN RIGHT"))
        self.btn_Backward.setText(_translate("MainWindow", "BACKWARD"))
        self.label_tAngle.setText(_translate("MainWindow", "Turning angle"))
        self.btn_Connect.setText(_translate("MainWindow", "Connect"))
        self.label_Speed.setText(_translate("MainWindow", "Speed"))
        self.label_Scale.setText(_translate("MainWindow", "Scale"))
        self.label_IP_Addr.setText(_translate("MainWindow", "Server IP Address"))
        self.btn_RGB_R.setText(_translate("MainWindow", "RGB_R"))
        self.btn_RGB_G.setText(_translate("MainWindow", "RGB_G"))
        self.btn_RGB_B.setText(_translate("MainWindow", "RGB_B"))
        self.btn_Buzzer.setText(_translate("MainWindow", "Buzzer"))
        self.groupBox_Servo.setTitle(_translate("MainWindow", "Servo Fine Tuning"))
        self.label_FineServo_1.setText(_translate("MainWindow", "Servo1"))
        self.label_FineServo_2.setText(_translate("MainWindow", "Servo2"))
        self.label_FineServo_3.setText(_translate("MainWindow", "Servo3"))
        self.label_FineServo_4.setText(_translate("MainWindow", "Servo4"))
        self.btn_Home.setText(_translate("MainWindow", "HOME"))
        self.btn_Mode.setText(_translate("MainWindow", "VIDEO"))
        self.label_Mode.setText(_translate("MainWindow", "MODE"))
from PyQt5 import QtWebKitWidgets

import fn_logo_rc
